= C++ Design Patterns
:toc:
:toc-placement!:

toc::[]

# Introduction

This demonstrates:

    * Modern C++ Design Patterns
    * Modern C++ techniques
    * Modern C++ features (11, 14, 17)

The example also shows how to setup a CMake project which includes sub-projects.

# Pre-requisites

You should have the following installed:

  * Git
  * CLion
  * CMake
  * Boost (on the path or in Mingw)
  * Valgrind (We will do some Modern C++ concurrency in a few sections)
  * gcc (Windows Mingw, Mac CLang or gcc)

## Mac install:

<<env/mac-env.adoc#title, Mac Install>>

## Ubuntu install:

<<env/ubuntu-env.adoc#title, Ubuntu Install>>

## Windows install:

<<env/windows-env.adoc#title, Windows Install>>

# Sub-Projects

SOLID Design <<solid-cpp/README.adoc#title, README>>

Creational Patterns <<creational-cpp/README.adoc#title, README>>

# CLion Project

https://www.jetbrains.com/help/clion/meet-clion.html[Get used to CLion]

https://www.jetbrains.com/help/clion/quick-tutorial-on-configuring-clion-on-windows.html[Configure CLion on Windows]

# Using Git

https://www.atlassian.com/git/tutorials/atlassian-git-cheatsheet[Git commands cheat sheet]

# Command-Line Build

$ cd into the directory

[source, cmake]
----
$cd design-patterns-cpp
----

Run cmake against the CMakeLists.txt.  Assume this is *nix environment and case sensitive.

[source, cmake]
----
$cmake CMakeLists.txt
----

When it's done, run make to build the executables.
[source, cmake]
----
$make
----

# Unit Testing

<<req/requirements-unit-testing.adoc#title, Unit Testing>>

# Packaging

<<req/requirements-packaging.adoc#title, Packaging>>

# Static Analysis

<<req/requirements-static-analysis.adoc#title, Static Analysis>>

# Directory Structure

<<requirements-directory-structure.adoc#title, Requirements for directory structure>>









